name: 'Edward T. Rostick & Associates'
favicon: null
layout_spectrum: 0.2887333142571151
typography_spectrum: 0.9123999897856265
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.3527657287195325
  lightness: 0.10421797959133983
  saturation: 0.4652779509779066
  rhythmicContrast: 0.9259691261686385
purpose: []
